#!/bin/bash

if [ "$#" -lt 1 ]; then
    printf "Usage: $script_name APP_DIR\n"
    exit 1
fi

app_dir=$(pwd)/$1
log_dir=$app_dir/shinylog

if [ ! -d $app_dir ]; then
    echo "Supply app dir path"
    exit 1
fi

docker run -ti --rm --name rs -p 63112:3838 \
    -v $app_dir:/srv/shiny-server/ \
    -v $(pwd)/shiny-server.conf:/etc/shiny-server/shiny-server.conf \
    -v $log_dir:/var/log/shiny-server/ \
    crowjdh/rshiny-korean:dependencies /init
